In [1]:
import pandas as pd

In [ ]:
arquivo = "financial_data.csv"

In [ ]:
# verificando o Dataframe 
analise = pd.read_csv(arquivo)
display(analise)

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,Government,Canada,Carretera,None,"$1,618.50",$3.00,$20.00,"$32,370.00",$-,"$32,370.00","$16,185.00","$16,185.00",1/1/2014,1,January,2014
1,Government,Germany,Carretera,None,"$1,321.00",$3.00,$20.00,"$26,420.00",$-,"$26,420.00","$13,210.00","$13,210.00",1/1/2014,1,January,2014
2,Midmarket,France,Carretera,None,"$2,178.00",$3.00,$15.00,"$32,670.00",$-,"$32,670.00","$21,780.00","$10,890.00",6/1/2014,6,June,2014
3,Midmarket,Germany,Carretera,None,$888.00,$3.00,$15.00,"$13,320.00",$-,"$13,320.00","$8,880.00","$4,440.00",6/1/2014,6,June,2014
4,Midmarket,Mexico,Carretera,None,"$2,470.00",$3.00,$15.00,"$37,050.00",$-,"$37,050.00","$24,700.00","$12,350.00",6/1/2014,6,June,2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,Small Business,France,Amarilla,High,"$2,475.00",$260.00,$300.00,"$742,500.00","$111,375.00","$631,125.00","$618,750.00","$12,375.00",3/1/2014,3,March,2014
696,Small Business,Mexico,Amarilla,High,$546.00,$260.00,$300.00,"$163,800.00","$24,570.00","$139,230.00","$136,500.00","$2,730.00",10/1/2014,10,October,2014
697,Government,Mexico,Montana,High,"$1,368.00",$5.00,$7.00,"$9,576.00","$1,436.40","$8,139.60","$6,840.00","$1,299.60",2/1/2014,2,February,2014
698,Government,Canada,Paseo,High,$723.00,$10.00,$7.00,"$5,061.00",$759.15,"$4,301.85","$3,615.00",$686.85,4/1/2014,4,April,2014
699,Channel Partners,United States of America,VTT,High,"$1,806.00",$250.00,$12.00,"$21,672.00","$3,250.80","$18,421.20","$5,418.00","$13,003.20",5/1/2014,5,May,2014

In [ ]:
# obtendo info do Dataframe 
analise.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Segment                700 non-null    object
 1   Country                700 non-null    object
 2    Product               700 non-null    object
 3    Discount Band         700 non-null    object
 4    Units Sold            700 non-null    object
 5    Manufacturing Price   700 non-null    object
 6    Sale Price            700 non-null    object
 7    Gross Sales           700 non-null    object
 8    Discounts             700 non-null    object
 9     Sales                700 non-null    object
 10   COGS                  700 non-null    object
 11   Profit                700 non-null    object
 12  Date                   700 non-null    object
 13  Month Number           700 non-null    int64
 14   Month Name            700 non-null    object
 15  Year                   700 non-null    int64
dtypes: int64(2), object(14)
memory usage: 87.6+ KB

In [10]:
print("NÃºmero de linhas duplicadas:", analise.duplicated().sum())

NÃºmero de linhas duplicadas: 0

In [ ]:
# Analisando o tipo das colunas 
analise.dtypes

Segment                  object
Country                  object
 Product                 object
 Discount Band           object
 Units Sold              object
 Manufacturing Price     object
 Sale Price              object
 Gross Sales             object
 Discounts               object
  Sales                  object
 COGS                    object
 Profit                  object
Date                     object
Month Number              int64
 Month Name              object
Year                      int64
dtype: object

In [12]:
analise.value_counts()

Segment           Country                    Product     Discount Band    Units Sold    Manufacturing Price    Sale Price    Gross Sales    Discounts       Sales         COGS           Profit        Date       Month Number   Month Name   Year
Channel Partners  Canada                     Amarilla    High             $2,761.00     $260.00                $12.00        $33,132.00     $3,975.84      $29,156.16     $8,283.00      $20,873.16    9/1/2013   9              September    2013    1
Government        United States of America   Paseo       Low              $274.00       $10.00                 $350.00       $95,900.00     $3,836.00      $92,064.00     $71,240.00     $20,824.00    12/1/2014  12             December     2014    1
                                                         High             $1,177.00     $10.00                 $350.00       $411,950.00    $57,673.00     $354,277.00    $306,020.00    $48,257.00    11/1/2014  11             November     2014    1
                                                                          $1,438.50     $10.00                 $7.00         $10,069.50     $1,309.04      $8,760.47      $7,192.50      $1,567.96     1/1/2014   1              January      2014    1
                                                                          $2,007.00     $10.00                 $350.00       $702,450.00    $105,367.50    $597,082.50    $521,820.00    $75,262.50    11/1/2013  11             November     2013    1
                                                                                                                                                                                                                                                     ..
                  Canada                     Paseo       Low              $2,852.00     $10.00                 $350.00       $998,200.00    $19,964.00     $978,236.00    $741,520.00    $236,716.00   12/1/2014  12             December     2014    1
                                                                          $4,251.00     $10.00                 $7.00         $29,757.00     $1,190.28      $28,566.72     $21,255.00     $7,311.72     1/1/2014   1              January      2014    1
                                                         Medium           $1,228.00     $10.00                 $350.00       $429,800.00    $21,490.00     $408,310.00    $319,280.00    $89,030.00    10/1/2013  10             October      2013    1
                                                                          $1,389.00     $10.00                 $20.00        $27,780.00     $1,389.00      $26,391.00     $13,890.00     $12,501.00    10/1/2013  10             October      2013    1
Small Business    United States of America   Velo        Medium           $1,372.00     $120.00                $300.00       $411,600.00    $28,812.00     $382,788.00    $343,000.00    $39,788.00    12/1/2014  12             December     2014    1
Length: 700, dtype: int64

In [14]:
#Verificando se ha valores nulos nas colunas 
analise.isna().sum()

Segment                  0
Country                  0
 Product                 0
 Discount Band           0
 Units Sold              0
 Manufacturing Price     0
 Sale Price              0
 Gross Sales             0
 Discounts               0
  Sales                  0
 COGS                    0
 Profit                  0
Date                     0
Month Number             0
 Month Name              0
Year                     0
dtype: int64